// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/(dashboard)/academy/lesson/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/academy/lesson/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/academy/lesson/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/academy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/academy">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/academy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/academy/quiz/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/academy/quiz/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/academy/quiz/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/defi/opportunities/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/defi/opportunities">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/defi/opportunities/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/derivatives/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/derivatives">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/derivatives/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/equities/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/equities">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/equities/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/etf-flows/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/etf-flows">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/etf-flows/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/lineage/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lineage">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/lineage/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/markets/compare/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/markets/compare">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/markets/compare/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/markets/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/markets">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/markets/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/news/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/news">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/news/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/onchain/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/onchain">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/onchain/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/oracle/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/oracle">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/oracle/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reports">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/research/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/research">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/research/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/security/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/security">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/security/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/test-report/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/test-report">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/test-report/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/wallstreet/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wallstreet">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/wallstreet/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(oracle)/vox-war-room/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vox-war-room">> = Specific
  const handler = {} as typeof import("../../src/app/(oracle)/vox-war-room/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/alerts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/alerts">> = Specific
  const handler = {} as typeof import("../../src/app/alerts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/control/compliance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/control/compliance">> = Specific
  const handler = {} as typeof import("../../src/app/control/compliance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/control/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/control">> = Specific
  const handler = {} as typeof import("../../src/app/control/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard-backup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard-backup">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard-backup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard-simple/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard-simple">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard-simple/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard-test/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard-test">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard-test/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dqp/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dqp">> = Specific
  const handler = {} as typeof import("../../src/app/dqp/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/monitoring/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/monitoring">> = Specific
  const handler = {} as typeof import("../../src/app/monitoring/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/opx/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/opx">> = Specific
  const handler = {} as typeof import("../../src/app/opx/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/pnl/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pnl">> = Specific
  const handler = {} as typeof import("../../src/app/pnl/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/simple/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/simple">> = Specific
  const handler = {} as typeof import("../../src/app/simple/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/test-components/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/test-components">> = Specific
  const handler = {} as typeof import("../../src/app/test-components/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/test-simple/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/test-simple">> = Specific
  const handler = {} as typeof import("../../src/app/test-simple/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/actions/alerts/[alert_id]/ack/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/actions/alerts/[alert_id]/ack">> = Specific
  const handler = {} as typeof import("../../src/app/api/actions/alerts/[alert_id]/ack/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/actions/dqp/ack/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/actions/dqp/ack">> = Specific
  const handler = {} as typeof import("../../src/app/api/actions/dqp/ack/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/actions/dqp/retry/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/actions/dqp/retry">> = Specific
  const handler = {} as typeof import("../../src/app/api/actions/dqp/retry/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/actions/opps/[opp_id]/status/[status]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/actions/opps/[opp_id]/status/[status]">> = Specific
  const handler = {} as typeof import("../../src/app/api/actions/opps/[opp_id]/status/[status]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/actions/opx/approve/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/actions/opx/approve">> = Specific
  const handler = {} as typeof import("../../src/app/api/actions/opx/approve/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/actions/opx/reject/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/actions/opx/reject">> = Specific
  const handler = {} as typeof import("../../src/app/api/actions/opx/reject/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/actions/report/deliver/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/actions/report/deliver">> = Specific
  const handler = {} as typeof import("../../src/app/api/actions/report/deliver/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/agents/process/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agents/process">> = Specific
  const handler = {} as typeof import("../../src/app/api/agents/process/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/alert/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/alert">> = Specific
  const handler = {} as typeof import("../../src/app/api/alert/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/allocator/meta/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/allocator/meta">> = Specific
  const handler = {} as typeof import("../../src/app/api/allocator/meta/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/alpha/factory/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/alpha/factory">> = Specific
  const handler = {} as typeof import("../../src/app/api/alpha/factory/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/blockspace/builder/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/blockspace/builder">> = Specific
  const handler = {} as typeof import("../../src/app/api/blockspace/builder/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/blockspace/desk/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/blockspace/desk">> = Specific
  const handler = {} as typeof import("../../src/app/api/blockspace/desk/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/blockspace/rebates/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/blockspace/rebates">> = Specific
  const handler = {} as typeof import("../../src/app/api/blockspace/rebates/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/blockspace/routes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/blockspace/routes">> = Specific
  const handler = {} as typeof import("../../src/app/api/blockspace/routes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/blockspace/sequencer/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/blockspace/sequencer">> = Specific
  const handler = {} as typeof import("../../src/app/api/blockspace/sequencer/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/control/compliance/checklist/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/control/compliance/checklist">> = Specific
  const handler = {} as typeof import("../../src/app/api/control/compliance/checklist/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/control/keys/disable/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/control/keys/disable">> = Specific
  const handler = {} as typeof import("../../src/app/api/control/keys/disable/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/control/keys/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/control/keys">> = Specific
  const handler = {} as typeof import("../../src/app/api/control/keys/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/control/limits/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/control/limits">> = Specific
  const handler = {} as typeof import("../../src/app/api/control/limits/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/control/opx/score/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/control/opx/score">> = Specific
  const handler = {} as typeof import("../../src/app/api/control/opx/score/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/control/rules/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/control/rules">> = Specific
  const handler = {} as typeof import("../../src/app/api/control/rules/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/defi/opportunities/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/defi/opportunities">> = Specific
  const handler = {} as typeof import("../../src/app/api/defi/opportunities/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/equities/backtest/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/equities/backtest">> = Specific
  const handler = {} as typeof import("../../src/app/api/equities/backtest/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/equities/fundamentals/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/equities/fundamentals">> = Specific
  const handler = {} as typeof import("../../src/app/api/equities/fundamentals/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/equities/recommendations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/equities/recommendations">> = Specific
  const handler = {} as typeof import("../../src/app/api/equities/recommendations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/equities/signals/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/equities/signals">> = Specific
  const handler = {} as typeof import("../../src/app/api/equities/signals/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/events/alpha/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/events/alpha">> = Specific
  const handler = {} as typeof import("../../src/app/api/events/alpha/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/farside/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/farside">> = Specific
  const handler = {} as typeof import("../../src/app/api/farside/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/generate/report/onepager/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/generate/report/onepager">> = Specific
  const handler = {} as typeof import("../../src/app/api/generate/report/onepager/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/generate/report/quarterly/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/generate/report/quarterly">> = Specific
  const handler = {} as typeof import("../../src/app/api/generate/report/quarterly/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/health/app/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health/app">> = Specific
  const handler = {} as typeof import("../../src/app/api/health/app/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/health/db/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health/db">> = Specific
  const handler = {} as typeof import("../../src/app/api/health/db/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/health/redis/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health/redis">> = Specific
  const handler = {} as typeof import("../../src/app/api/health/redis/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../src/app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/healthz/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/healthz">> = Specific
  const handler = {} as typeof import("../../src/app/api/healthz/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ingest/etf/flow/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ingest/etf/flow">> = Specific
  const handler = {} as typeof import("../../src/app/api/ingest/etf/flow/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ingest/news/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ingest/news">> = Specific
  const handler = {} as typeof import("../../src/app/api/ingest/news/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ingest/onchain/tvl/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ingest/onchain/tvl">> = Specific
  const handler = {} as typeof import("../../src/app/api/ingest/onchain/tvl/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/integrations/summer/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integrations/summer">> = Specific
  const handler = {} as typeof import("../../src/app/api/integrations/summer/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/learn/exercise/run/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/learn/exercise/run">> = Specific
  const handler = {} as typeof import("../../src/app/api/learn/exercise/run/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/learn/lesson/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/learn/lesson/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/learn/lesson/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/learn/lessons/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/learn/lessons">> = Specific
  const handler = {} as typeof import("../../src/app/api/learn/lessons/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/learn/progress/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/learn/progress">> = Specific
  const handler = {} as typeof import("../../src/app/api/learn/progress/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/learn/quiz/submit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/learn/quiz/submit">> = Specific
  const handler = {} as typeof import("../../src/app/api/learn/quiz/submit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/liquidity/backstop/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/liquidity/backstop">> = Specific
  const handler = {} as typeof import("../../src/app/api/liquidity/backstop/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/metrics/lineage/view/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/metrics/lineage/view">> = Specific
  const handler = {} as typeof import("../../src/app/api/metrics/lineage/view/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/metrics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/metrics">> = Specific
  const handler = {} as typeof import("../../src/app/api/metrics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/metrics/ui/event/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/metrics/ui/event">> = Specific
  const handler = {} as typeof import("../../src/app/api/metrics/ui/event/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/metrics/wsp/integration-click/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/metrics/wsp/integration-click">> = Specific
  const handler = {} as typeof import("../../src/app/api/metrics/wsp/integration-click/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/metrics/wsp/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/metrics/wsp">> = Specific
  const handler = {} as typeof import("../../src/app/api/metrics/wsp/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/mm/selective/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mm/selective">> = Specific
  const handler = {} as typeof import("../../src/app/api/mm/selective/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/multichain/cosmos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/multichain/cosmos">> = Specific
  const handler = {} as typeof import("../../src/app/api/multichain/cosmos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/news/oracle/run/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/news/oracle/run">> = Specific
  const handler = {} as typeof import("../../src/app/api/news/oracle/run/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/news/oracle/standby/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/news/oracle/standby">> = Specific
  const handler = {} as typeof import("../../src/app/api/news/oracle/standby/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/news/oracle/triage/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/news/oracle/triage">> = Specific
  const handler = {} as typeof import("../../src/app/api/news/oracle/triage/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ops/retention/run/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ops/retention/run">> = Specific
  const handler = {} as typeof import("../../src/app/api/ops/retention/run/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/oracle/v1/metrics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/oracle/v1/metrics">> = Specific
  const handler = {} as typeof import("../../src/app/api/oracle/v1/metrics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/read/alerts.csv/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/read/alerts.csv">> = Specific
  const handler = {} as typeof import("../../src/app/api/read/alerts.csv/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/read/alerts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/read/alerts">> = Specific
  const handler = {} as typeof import("../../src/app/api/read/alerts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/read/audit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/read/audit">> = Specific
  const handler = {} as typeof import("../../src/app/api/read/audit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/read/compliance/checklist/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/read/compliance/checklist">> = Specific
  const handler = {} as typeof import("../../src/app/api/read/compliance/checklist/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/read/derivs/funding/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/read/derivs/funding">> = Specific
  const handler = {} as typeof import("../../src/app/api/read/derivs/funding/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/read/derivs/gamma/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/read/derivs/gamma">> = Specific
  const handler = {} as typeof import("../../src/app/api/read/derivs/gamma/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/read/dqp/incidents/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/read/dqp/incidents">> = Specific
  const handler = {} as typeof import("../../src/app/api/read/dqp/incidents/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/read/dqp/overview.csv/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/read/dqp/overview.csv">> = Specific
  const handler = {} as typeof import("../../src/app/api/read/dqp/overview.csv/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/read/dqp/overview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/read/dqp/overview">> = Specific
  const handler = {} as typeof import("../../src/app/api/read/dqp/overview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/read/etf/flow/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/read/etf/flow">> = Specific
  const handler = {} as typeof import("../../src/app/api/read/etf/flow/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/read/etf/flow2/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/read/etf/flow2">> = Specific
  const handler = {} as typeof import("../../src/app/api/read/etf/flow2/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/read/kpi/alerts7d/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/read/kpi/alerts7d">> = Specific
  const handler = {} as typeof import("../../src/app/api/read/kpi/alerts7d/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/read/kpi/limits/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/read/kpi/limits">> = Specific
  const handler = {} as typeof import("../../src/app/api/read/kpi/limits/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/read/kpi/nav/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/read/kpi/nav">> = Specific
  const handler = {} as typeof import("../../src/app/api/read/kpi/nav/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/read/kpi/pnl-buckets/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/read/kpi/pnl-buckets">> = Specific
  const handler = {} as typeof import("../../src/app/api/read/kpi/pnl-buckets/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/read/lineage/by-signal/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/read/lineage/by-signal">> = Specific
  const handler = {} as typeof import("../../src/app/api/read/lineage/by-signal/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/read/lineage/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/read/lineage/search">> = Specific
  const handler = {} as typeof import("../../src/app/api/read/lineage/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/read/lineage/trace/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/read/lineage/trace">> = Specific
  const handler = {} as typeof import("../../src/app/api/read/lineage/trace/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/read/news/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/read/news">> = Specific
  const handler = {} as typeof import("../../src/app/api/read/news/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/read/onchain/tvl-heatmap/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/read/onchain/tvl-heatmap">> = Specific
  const handler = {} as typeof import("../../src/app/api/read/onchain/tvl-heatmap/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/read/opportunities/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/read/opportunities">> = Specific
  const handler = {} as typeof import("../../src/app/api/read/opportunities/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/read/opx/list/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/read/opx/list">> = Specific
  const handler = {} as typeof import("../../src/app/api/read/opx/list/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/read/opx/plan/artifact/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/read/opx/plan/artifact">> = Specific
  const handler = {} as typeof import("../../src/app/api/read/opx/plan/artifact/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/read/opx/plan/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/read/opx/plan">> = Specific
  const handler = {} as typeof import("../../src/app/api/read/opx/plan/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/read/opx/plan/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/read/opx/plan/status">> = Specific
  const handler = {} as typeof import("../../src/app/api/read/opx/plan/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/read/opx/plan/task/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/read/opx/plan/task">> = Specific
  const handler = {} as typeof import("../../src/app/api/read/opx/plan/task/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/read/opx/plan/upsert/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/read/opx/plan/upsert">> = Specific
  const handler = {} as typeof import("../../src/app/api/read/opx/plan/upsert/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/read/oracle/dq/summary/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/read/oracle/dq/summary">> = Specific
  const handler = {} as typeof import("../../src/app/api/read/oracle/dq/summary/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/read/oracle/guardrails/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/read/oracle/guardrails">> = Specific
  const handler = {} as typeof import("../../src/app/api/read/oracle/guardrails/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/read/oracle/rpc/heartbeats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/read/oracle/rpc/heartbeats">> = Specific
  const handler = {} as typeof import("../../src/app/api/read/oracle/rpc/heartbeats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/read/report/kpis/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/read/report/kpis">> = Specific
  const handler = {} as typeof import("../../src/app/api/read/report/kpis/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/read/report/por/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/read/report/por">> = Specific
  const handler = {} as typeof import("../../src/app/api/read/report/por/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/read/report/summary/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/read/report/summary">> = Specific
  const handler = {} as typeof import("../../src/app/api/read/report/summary/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/read/reports/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/read/reports/health">> = Specific
  const handler = {} as typeof import("../../src/app/api/read/reports/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/read/reports/history/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/read/reports/history">> = Specific
  const handler = {} as typeof import("../../src/app/api/read/reports/history/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/read/risk/dd/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/read/risk/dd">> = Specific
  const handler = {} as typeof import("../../src/app/api/read/risk/dd/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/read/risk/var/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/read/risk/var">> = Specific
  const handler = {} as typeof import("../../src/app/api/read/risk/var/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/read/whoami/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/read/whoami">> = Specific
  const handler = {} as typeof import("../../src/app/api/read/whoami/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/research/backtest/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/research/backtest/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/research/backtest/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/research/backtest/promote/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/research/backtest/promote">> = Specific
  const handler = {} as typeof import("../../src/app/api/research/backtest/promote/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/research/backtest/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/research/backtest">> = Specific
  const handler = {} as typeof import("../../src/app/api/research/backtest/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/research/backtest/run/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/research/backtest/run">> = Specific
  const handler = {} as typeof import("../../src/app/api/research/backtest/run/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/research/backtests/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/research/backtests">> = Specific
  const handler = {} as typeof import("../../src/app/api/research/backtests/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/security/csp-report/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/security/csp-report">> = Specific
  const handler = {} as typeof import("../../src/app/api/security/csp-report/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/stream/alerts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stream/alerts">> = Specific
  const handler = {} as typeof import("../../src/app/api/stream/alerts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/system/validate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/system/validate">> = Specific
  const handler = {} as typeof import("../../src/app/api/system/validate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tca/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tca">> = Specific
  const handler = {} as typeof import("../../src/app/api/tca/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/vaults/lav/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vaults/lav">> = Specific
  const handler = {} as typeof import("../../src/app/api/vaults/lav/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/volpro/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/volpro">> = Specific
  const handler = {} as typeof import("../../src/app/api/volpro/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/wsp/calendar/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/wsp/calendar">> = Specific
  const handler = {} as typeof import("../../src/app/api/wsp/calendar/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/wsp/etf/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/wsp/etf">> = Specific
  const handler = {} as typeof import("../../src/app/api/wsp/etf/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/wsp/events/cooldown/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/wsp/events/cooldown">> = Specific
  const handler = {} as typeof import("../../src/app/api/wsp/events/cooldown/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/wsp/events/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/wsp/events">> = Specific
  const handler = {} as typeof import("../../src/app/api/wsp/events/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/wsp/indices/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/wsp/indices">> = Specific
  const handler = {} as typeof import("../../src/app/api/wsp/indices/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/wsp/ratesfx/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/wsp/ratesfx">> = Specific
  const handler = {} as typeof import("../../src/app/api/wsp/ratesfx/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/wsp/wsps/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/wsp/wsps">> = Specific
  const handler = {} as typeof import("../../src/app/api/wsp/wsps/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/(dashboard)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
