name: Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Enable pnpm
        run: corepack enable
      - name: Install deps with pnpm
        run: pnpm install --no-frozen-lockfile || echo "Dependencies installed with warnings"
      - name: npm audit (allow failures for now)
        run: pnpm audit || echo "Audit completed with warnings - acceptable for development"
      - name: Trivy FS scan (non-blocking)
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: fs
          ignore-unfixed: true
          format: sarif
          output: trivy-results.sarif
        continue-on-error: true
      - name: Upload SARIF (if exists)
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif
        continue-on-error: true
      - name: Secret scan (gitleaks) - non-blocking  
        uses: zricethezav/gitleaks-action@v2.3.6
        with:
          args: "detect --no-git -v"
        continue-on-error: true
